<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="lapdell-0235" failures="0" tests="3" name="org.verifyFillFormAndAddToCart" time="20.165" errors="1" timestamp="22 Sep 2023 02:17:06 GMT" skipped="2">
  <testcase classname="org.verifyFillFormAndAddToCart" name="verifyFillFormAndAddToCart" time="0.000">
    <skipped/>
  </testcase> <!-- verifyFillFormAndAddToCart -->
  <testcase classname="org.verifyFillFormAndAddToCart" name="ConfigureAppium" time="20.165">
    <error message="The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\quy.buithi\AppData\Roaming\npm\node_modules\appium, --port, 4723, --address, 127.0.0.1, --log, D:\PTC_Appium_POC\AppiumFrameworkDesignappium.log] 
Process output: Tried to attach logging to file &#039;D:\PTC_Appium_POC\AppiumFrameworkDesignappium.log&#039; but an error occurred: EBUSY: resource busy or locked, unlink &#039;D:\PTC_Appium_POC\AppiumFrameworkDesignappium.log&#039;
[35m[Appium][39m Welcome to Appium v2.1.3
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m&#039;127.0.0.1&#039;[39m }
[35m[Appium][39m Attempting to load driver uiautomator2...
[debug] [35m[Appium][39m Requiring driver at C:\Users\quy.buithi\.appium\node_modules\appium-uiautomator2-driver

" type="io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException">
      <![CDATA[io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\quy.buithi\AppData\Roaming\npm\node_modules\appium, --port, 4723, --address, 127.0.0.1, --log, D:\PTC_Appium_POC\AppiumFrameworkDesignappium.log] 
Process output: Tried to attach logging to file 'D:\PTC_Appium_POC\AppiumFrameworkDesignappium.log' but an error occurred: EBUSY: resource busy or locked, unlink 'D:\PTC_Appium_POC\AppiumFrameworkDesignappium.log'
[35m[Appium][39m Welcome to Appium v2.1.3
[35m[Appium][39m Non-default server args:
[35m[Appium][39m { address: [32m'127.0.0.1'[39m }
[35m[Appium][39m Attempting to load driver uiautomator2...
[debug] [35m[Appium][39m Requiring driver at C:\Users\quy.buithi\.appium\node_modules\appium-uiautomator2-driver


at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:182)
at org.utils.AppiumUtils.startAppiumServer(AppiumUtils.java:71)
at org.TestUtils.AndroidBaseTest.ConfigureAppium(AndroidBaseTest.java:67)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://127.0.0.1:4723/status] to be available after 20012 ms
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:94)
at io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:147)
at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:169)
... 28 more
Caused by: java.util.concurrent.TimeoutException
at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:91)
... 30 more
]]>
    </error>
  </testcase> <!-- ConfigureAppium -->
  <testcase classname="org.verifyFillFormAndAddToCart" name="verifyFillFormAndAddToCart" time="0.000">
    <skipped/>
  </testcase> <!-- verifyFillFormAndAddToCart -->
</testsuite> <!-- org.verifyFillFormAndAddToCart -->
